server.port: 6767
spring:
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/M295-TrainTrack-Backend
app:
  name: M295-TrainTrack-Backend